version: '3.9'

services:

  replica_1:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "10001:10001"
    volumes:
      - ./config:/config
      - ./logs:/logs
    command: ["--name", "1", "--configPath", "/config/config.json"]
    networks:
      - net1
    restart: "no"

  replica_2:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "10002:10002"
    volumes:
      - ./config:/config
      - ./logs:/logs
    command: ["--name", "2", "--configPath", "/config/config.json"]
    networks:
      - net2
    restart: "no"

  replica_3:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "10003:10003"
    volumes:
      - ./config:/config
      - ./logs:/logs
    command: ["--name", "3", "--configPath", "/config/config.json"]
    networks:
      - net3
    restart: "no"

  replica_4:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "10004:10004"
    volumes:
      - ./config:/config
      - ./logs:/logs
    command: ["--name", "4", "--configPath", "/config/config.json"]
    networks:
      - net4
    restart: "no"

  replica_5:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "10005:10005"
    volumes:
      - ./config:/config
      - ./logs:/logs
    command: ["--name", "5", "--configPath", "/config/config.json"]
    networks:
      - net5
    restart: "no"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    volumes:
      - ./config:/config
      - ./logs:/logs
    depends_on:
      - replica_1
      - replica_2
      - replica_3
      - replica_4
      - replica_5
    command: ["--name", "10", "--configPath", "/config/config.json", "--duration", "60"]
    networks:
      - netc
    restart: "no"

networks:
  net1:
  net2:
  net3:
  net4:
  net5:
  netc: